// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import { defineConfig } from 'prisma/config'

export default defineConfig({
  datasource: {
    url: "postgresql://postgres.wfnevcyuoydrumdxaamn:FylhtqUbnkth123@aws-0-eu-west-1.pooler.supabase.com:5432/postgres",
  },
  migrations: {
    path: "prisma/migrations",
  },
  schema: "prisma/schema.prisma",
});
